<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <AssemblyName>IGTAP.Ultras</AssemblyName>
    <RootNamespace>IGTAP.EngineSim.Ultras</RootNamespace>
    <Nullable>disable</Nullable>
    <ImplicitUsings>disable</ImplicitUsings>
    <LangVersion>latest</LangVersion>
    <Optimize>true</Optimize>
    <ServerGarbageCollection>true</ServerGarbageCollection>
    <ConcurrentGarbageCollection>false</ConcurrentGarbageCollection>
    <TieredPGO>true</TieredPGO>
  </PropertyGroup>
  <ItemGroup>
    <RuntimeHostConfigurationOption Include="System.GC.HeapHardLimit" Value="75161927680" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="../Runtime/IGTAP.EngineSim.Runtime.csproj" />
    <Reference Include="Assembly-CSharp" HintPath="../obj/game/Assembly-CSharp.dll" Private="true" />
  </ItemGroup>
</Project>
