<Project>
  <PropertyGroup>
    <IgtapGame Condition="'$(IgtapGame)' == ''">$(IGTAP_GAME)</IgtapGame>
    <IgtapGame Condition="'$(IgtapGame)' == '' And '$(OS)' == 'Windows_NT'">C:\Program Files (x86)\Steam\steamapps\common\IGTAP an Incremental Game That's Also a Platformer</IgtapGame>
    <IgtapGame Condition="'$(IgtapGame)' == ''">$(HOME)/.local/share/Steam/steamapps/common/IGTAP an Incremental Game That's Also a Platformer</IgtapGame>
  </PropertyGroup>
</Project>
